<script lang="ts">
  // Footer import removed as it's now in the layout
</script>

<main class="min-h-screen bg-white w-full">
  <div class="px-12 md:px-24 py-20">
    <div class="max-w-[1280px] mx-auto">
      <h1 class="text-4xl md:text-5xl font-bold mb-8 font-rem">SOLEDA TERMS OF SERVICE</h1>
      <p class="text-gray-700 mb-12">Effective Date: April 9, 2025</p>

      <div class="space-y-12 text-gray-800">
        <!-- Section 1 -->
        <section>
          <h2 class="text-2xl font-bold mb-4">1. INTRODUCTION</h2>
          <p class="mb-4">
            Welcome to Soleda. These Terms of Service ("Terms") constitute a legally binding agreement between you ("User" or "you") and Soleda ("Company," "we," "us," or "our") governing your access to and use of our website, www.soleda.ai, and our AI-powered services, including but not limited to our AI agent, Dana (collectively, the "Services"). By accessing or using our Services, you acknowledge that you have read, understood, and agree to be bound by these Terms and our Privacy Policy. If you do not agree with these Terms, you must not use our Services.
          </p>
        </section>

        <!-- Section 2 -->
        <section>
          <h2 class="text-2xl font-bold mb-4">2. DEFINITIONS</h2>
          <p class="mb-2">
            "Services" refers to the website, www.soleda.ai, and all AI-powered services provided by Soleda, including the AI agent, Dana.
          </p>
          <p class="mb-2">
            "User" refers to any individual or entity that accesses or uses our Services.
          </p>
          <p class="mb-2">
            "Input Data" refers to any data, information, or content that you provide to the Services for processing.
          </p>
          <p class="mb-2">
            "Output Data" refers to any data, information, or content generated by the Services in response to your Input Data.
          </p>
        </section>

        <!-- Section 3 -->
        <section>
          <h2 class="text-2xl font-bold mb-4">3. SERVICES PROVIDED</h2>
          <p class="mb-4">
            Soleda offers AI-powered agents with domain expertise to assist users in specialized tasks. Our inaugural agent, Dana, is designed to support data analysts, particularly those in market growth teams, by facilitating the integration, cleaning, transformation, and analysis of customer data during interactive sessions.
          </p>
        </section>

        <!-- Section 4 -->
        <section>
          <h2 class="text-2xl font-bold mb-4">4. USER ELIGIBILITY AND RESPONSIBILITIES</h2>
          <p class="mb-2">
            <strong>Eligibility:</strong> You must be at least 18 years old to access or use our Services. By using our Services, you represent and warrant that you have the legal capacity to enter into these Terms.
          </p>
          <p class="mb-2">
            <strong>Account Security:</strong> If you create an account with us, you are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.
          </p>
          <p class="mb-2">
            <strong>Compliance:</strong> You agree to use our Services in compliance with all applicable laws, regulations, and these Terms. You are solely responsible for your conduct while using our Services.
          </p>
        </section>

        <!-- Section 5 -->
        <section>
          <h2 class="text-2xl font-bold mb-4">5. SUBSCRIPTION AND PAYMENT TERMS</h2>
          <p class="mb-2">
            <strong>Subscription Model:</strong> Access to certain features of our Services, including interactions with Dana, requires a subscription. We collaborate with clients to develop customized subscription plans tailored to their specific needs.
          </p>
          <p class="mb-2">
            <strong>Billing and Payment:</strong> Subscription fees, billing cycles, and payment terms will be specified in your subscription agreement. By subscribing, you agree to pay all applicable fees as outlined in your subscription plan.
          </p>
          <p class="mb-2">
            <strong>Changes to Fees:</strong> We reserve the right to modify our subscription fees upon reasonable notice to you. Continued use of the Services after such changes constitutes your acceptance of the new fees.
          </p>
        </section>

        <!-- Section 6 -->
        <section>
          <h2 class="text-2xl font-bold mb-4">6. DATA HANDLING AND PRIVACY</h2>
          <p class="mb-2">
            <strong>Session-Based Data Processing:</strong> Our Services process Input Data during active sessions only. Upon termination of a session, all Input Data, including any data imported from third-party platforms, is deleted and is not retained by Soleda. We do not store, share, or transfer this data to any third parties after the session ends, ensuring minimal data retention and compliance with data minimization principles. Input Data is not used to train our AI models.
          </p>
          <p class="mb-2">
            <strong>Personalization Data:</strong> While Input Data is deleted after each session, Dana may retain limited information derived from your interactions to enhance personalization and improve future user experiences.
          </p>
          <p class="mb-2">
            <strong>Data Ownership:</strong> You retain ownership of all Input Data you provide. By using our Services, you grant Soleda a non-exclusive, worldwide, royalty-free license to process your Input Data solely for the purpose of providing the Services.
          </p>
          <p class="mb-2">
            <strong>Legal Review of Data Requests:</strong> We are committed to ensuring that all requests for data disclosure comply with applicable laws and regulations. Prior to responding to any third-party request for data, including governmental or legal demands, we will review the legality of such requests. This review process may involve the use of advanced language models to assist in evaluating the request's validity and scope. We reserve the right to reject or limit any request that does not meet legal standards or exceeds the necessary scope.
          </p>
          <p class="mb-2">
            <strong>Documentation of Data Requests:</strong> We maintain a policy of documenting all requests for data access or disclosure received from third parties, including the nature of the request, the requesting entity, and our response. This documentation ensures transparency and accountability in our data handling practices and is retained for internal review and compliance purposes only, in accordance with applicable laws.
          </p>
          <p class="mb-2">
            <strong>Privacy Policy:</strong> Our commitment to your privacy is detailed in our Privacy Policy, which outlines how we collect, use, and protect your information. By using our Services, you consent to the practices described in the Privacy Policy. See our Privacy Policy for further details on data handling.
          </p>
        </section>

        <!-- Section 7 -->
        <section>
          <h2 class="text-2xl font-bold mb-4">7. USE OF AI-GENERATED CONTENT</h2>
          <p class="mb-2">
            <strong>Accuracy and Reliability:</strong> The Output Data generated by our AI agent, Dana, is based on the Input Data provided by you. While we strive for accuracy, AI-generated content may not always be correct or reliable. You should independently verify any Output Data before making decisions based on it.
          </p>
          <p class="mb-2">
            <strong>No Liability:</strong> Soleda assumes no responsibility for any errors or omissions in the Output Data or for any actions taken based on such content. You acknowledge that reliance on any Output Data is at your own risk.
          </p>
          <p class="mb-2">
            <strong>Public Sharing:</strong> You are permitted to share Output Data publicly, provided that such sharing complies with applicable laws and does not misrepresent the nature of the Services or imply endorsement by Soleda.
          </p>
        </section>

        <!-- Section 8 -->
        <section>
          <h2 class="text-2xl font-bold mb-4">8. PROHIBITED CONDUCT</h2>
          <p class="mb-4">You agree not to:</p>
          <ul class="list-disc pl-8 space-y-2">
            <li>Use the Services for any unlawful purpose or in violation of any local, state, national, or international law.</li>
            <li>Engage in any activity that could harm or interfere with the operation or security of the Services.</li>
            <li>Attempt to gain unauthorized access to any accounts, systems, or networks related to the Services.</li>
            <li>Reverse engineer, decompile, disassemble, or otherwise attempt to discover the source code of the Services.</li>
            <li>Use the Services to transmit any harmful or disruptive code, such as viruses or malware.</li>
          </ul>
        </section>

        <!-- Section 9 -->
        <section>
          <h2 class="text-2xl font-bold mb-4">9. MODIFICATIONS TO THE SERVICES AND TERMS</h2>
          <p class="mb-2">
            <strong>Service Changes:</strong> We reserve the right to modify or discontinue the Services, in whole or in part, at any time, with or without notice.
          </p>
          <p class="mb-2">
            <strong>Terms Updates:</strong> We may update these Terms from time to time. We will notify you of significant changes by posting the new Terms on our website and updating the effective date. Your continued use of the Services after such changes constitutes your acceptance of the revised Terms.
          </p>
        </section>

        <!-- Section 10 -->
        <section>
          <h2 class="text-2xl font-bold mb-4">10. TERMINATION</h2>
          <p class="mb-2">
            <strong>By You:</strong> You may terminate your use of the Services at any time by discontinuing access.
          </p>
          <p class="mb-2">
            <strong>By Soleda:</strong> We may suspend or terminate your access to the Services at our sole discretion, without prior notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties.
          </p>
          <p class="mb-2">
            <strong>Effect of Termination:</strong> Upon termination, all rights granted to you under these Terms will cease immediately. Sections that by their nature should survive termination shall survive, including but not limited to, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.
          </p>
        </section>

        <!-- Section 11 -->
        <section>
          <h2 class="text-2xl font-bold mb-4">11. DISCLAIMERS AND LIMITATION OF LIABILITY</h2>
          <p class="mb-2">
            <strong>As-Is Basis:</strong> The Services are provided on an "as-is" and "as-available" basis. Soleda disclaims all warranties, express or implied, including but not limited to merchantability, fitness for a particular purpose, and non-infringement.
          </p>
          <p class="mb-2">
            <strong>Limitation of Liability:</strong> To the fullest extent permitted by law, Soleda shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your use of the Services.
          </p>
        </section>

        <!-- Section 12 -->
        <section>
          <h2 class="text-2xl font-bold mb-4">12. INDEMNIFICATION</h2>
          <p class="mb-4">
            You agree to indemnify, defend, and hold harmless Soleda, its affiliates, officers, directors, employees, agents, and licensors from and against any claims, liabilities, damages, losses, and expenses, including reasonable attorneys' fees, arising out of or in any way connected with your access to or use of the Services, your violation of these Terms, or your infringement of any intellectual property or other rights of any third party.
          </p>
        </section>

        <!-- Section 13 -->
        <section>
          <h2 class="text-2xl font-bold mb-4">13. GOVERNING LAW AND DISPUTE RESOLUTION</h2>
          <p class="mb-2">
            <strong>Governing Law:</strong> These Terms and any dispute or claim arising out of or in connection with them shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of law provisions.
          </p>
          <p class="mb-2">
            <strong>Dispute Resolution:</strong> Any disputes arising under or in connection with these Terms shall be resolved through binding arbitration conducted in San Mateo County, California, in accordance with the rules of the American Arbitration Association. The arbitration shall be conducted by a single arbitrator, and judgment on the arbitration award may be entered in any court having jurisdiction.
          </p>
          <p class="mb-2">
            <strong>Injunctive Relief:</strong> Notwithstanding the foregoing, either party may seek injunctive or other equitable relief in a court of competent jurisdiction to prevent or stop unauthorized use or misuse of the Services or intellectual property infringement without first engaging in arbitration.
          </p>
        </section>

        <!-- Section 14 -->
        <section>
          <h2 class="text-2xl font-bold mb-4">14. MISCELLANEOUS</h2>
          <p class="mb-2">
            <strong>Entire Agreement:</strong> These Terms, along with our Privacy Policy and any additional agreements expressly incorporated herein, constitute the entire agreement between you and Soleda concerning your access to and use of the Services and supersede any prior or contemporaneous communications or agreements.
          </p>
          <p class="mb-2">
            <strong>Waiver and Severability:</strong> Our failure to enforce any right or provision of these Terms will not be considered a waiver of such right or provision. If any provision of these Terms is held to be invalid or unenforceable, the remaining provisions will remain in full force and effect.
          </p>
          <p class="mb-2">
            <strong>Assignment:</strong> You may not assign or transfer your rights or obligations under these Terms without our prior written consent. We may freely assign or transfer our rights and obligations without restriction.
          </p>
          <p class="mb-2">
            <strong>Force Majeure:</strong> We shall not be held liable for any delay or failure to perform resulting from causes outside our reasonable control, including but not limited to acts of God, war, terrorism, labor disputes, natural disasters, pandemics, or governmental actions.
          </p>
        </section>

        <!-- Section 15 -->
        <section>
          <h2 class="text-2xl font-bold mb-4">15. CONTACT INFORMATION</h2>
          <p class="mb-4">
            If you have any questions or concerns about these Terms, please contact us at:
          </p>
          <div class="pl-4 border-l-4 border-gray-200 py-2">
            <p><a href="mailto:support@soleda.ai" class="text-[#006BB9] hover:underline">support@soleda.ai</a></p>
          </div>
        </section>
      </div>
    </div>
  </div>
</main>

<style>
  section p {
    line-height: 1.6;
  }
</style>